[project]
name = "commonsense_combiner"
authors = [
    {name = "Oliver R. Fox", email= "o.fox3@newcastle.ac.uk"}
]
version = "1.0.0"
description = "."
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "psycopg2",
    "pyyaml",
    "requests",
    "rdflib",
    "tqdm",
    "dacite",
    "nltk"
]

[project.scripts]
build-ontology = "build_ontology:main"

[tool.setuptools]
packages = ["knowledge_bases"]
py-modules = ["build_ontology"]
