[project]
name = "HOnK"
authors = [
    {name = "Oliver R. Fox", email= "o.fox3@newcastle.ac.uk"}
]
version = "1.5.0"
description = "."
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "psycopg2",
    "pyyaml",
    "requests",
    "rdflib",
    "tqdm",
    "dacite",
    "nltk",
    "pandas",
    "matplotlib",
    "plotnine",
    "psutil",
    "pytest",
    "pyyaml",
    "networkx",
    "pyoxigraph",
    "ollama",
    "scipy",
    "sentence-transformers"
]

[project.scripts]
build-ontology = "build_ontology:main"

[tool.setuptools]
packages = ["knowledge_bases", "benchmarking", "clustering", "supporting_files.parmenides.classes"]
py-modules = ["build_ontology"]
